services:
  - type: web
    name: portfolio
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
